QUE SIGNIFICA O M  NO PYTHON3 -M VENV VENV?


COMO ENCONTRAR A VERSAO DO PYTHON?


COMO FAZER O UPGRADE DO PYTHON?


COMO EXECUTAR UM PROGRAMA PYTHON?


COMO LISTAR TODAS AS VERSOES DO PYENV?


COMO MOSTRAR QUAIS PYTHONS ESTAO INSTALADOS?


COMO DEFINIR O PYTHON PADRAO ATRAVES DO PYENV?


COMO FAZER UM TEXTO SER INTERPRETADO PELO PYTHON?


O DOCSTRING É UM COMENTARIO NO PYTHON?


COMO FUNCIONA O COMENTARIO NO INTERPRETADOR PYTHON?


-------------------------------------------------------------
SESSION 5

QUAL É UMA DAS PRIMEIRAS COISAS QUE É EXECUTADO QUANDO VOCE CHAMA A CLASSE?


COMO É CHAMADO A FUNÇÃO QUANDO ESTÁ DENTRO DA CLASSE?


QUAL É O PRIMEIRO PARAMETRO QUE PASSAMOS NO __INIT__?


COMO CRIAMOS UMA CLASSE PESSOA COM PARAMETROS DE NOME E SOBRENOME?


COMO COLOCAR COMPORTAMENTOS EM UMA CLASSE?


O METODO INIT RETORNA O QUE?


ESCREVA UMA CLASSE COM HARD CODED


O QUE É HARD CODED?


O QUE TODO METODO RECEBE COMO PRIMEIRO PARAMENTRO PARA REFERENCIAR A INSTANCIA NO PYTHON?


ESCREVA UMA CLASSE CARRO COM COMPORTAMENTO DE ACELERAR


O NOME SELF É UMA CONVENÇÃO?



---------------------------------------------------------------------------------------
UMA CLASSE PODE GERAR QUANTAS INSTANCIAS?


NA CLASSE O QUE É O SELF?


QUAL METODO É EXECUTADO QUANDO INSTANCIA A CLASSE?


DEFINA UMA VARIAVEL PARA SER EXECUTADA QUANDO INSTANCIAR A CLASSE SEM CHAMAR ESSA VARIAVEL


COMO É CHAMADO O ESCOPO DAS CLASSES E METODOS?


COMO DEFINIR ATRIBUTO DE CLASSE E ATRIBUTO DE INSTANCIA E COMO RETORNAR UM METODO DA CLASSE EM OUTRO METODO?



-------------------------------------------------------------------------------------------------------------------

ESCREVA UM CLASSE CAMERA PARA MANTER O ESTADOS (FILMAR, FOTOGRAFAR, PARA_DE_FILMAR) DENTRO DELA. REQUISITO DE QUANDO ESTIVER FILMANDO NÃO PODE FOTOGRAFAR

QUAIS AS DUAS MANEIRAS DE ACESSAR UM ATRIBUTO DE CLASSE?


ESCREVA UMA CLASSE COM ATRIBUTO DE ESCOPO DE CLASSE



---------------------------------------------------------------------------------------------

O QUE É O __DICT__?


COMO DELETAR UM DADO ATRIBUTO DE UMA CLASSE?


ONDE OS ATRIBUTOS DA CLASSE SÃO SALVOS?


QUAL A FUNÇÃO A QUE CONSEGUIMOS VER O __DICT__?


O __DICT__ É EDITAVEL? CONSTRUA UMA CLASSE!


CRIE UM DICIONARIO DE DADOS E DESEMPACOTE EM UMA CLASSE


PARA QUE SERVE O **KWARGS DO PYTHON?


CONSTRUA UMA CLASSE COM PROPRIEDADES E DEPOIS TENHA UM DICIONARIO DE DADOS E DESEMPACOTE ELES


---------------------------------------------

QUAL CONVENÇÃO DE NOME É UTILIZADA PARA CLASSE NO PYTHON?


QUAL CONVENÇÃO DE NOME É UTILIZADA PARA NOMES NO PYTHON?

 
CRIE UMA CLASSE PESSOA COM PROPRIEDADES DE NOME E SOBRENOME E SALVE OS DADOS DA CLASSE EM JSON


IMPORTE O MODULO CRIADO NO PYTHON PARA TER O CAMINHO DO ARQUIVO E FAÇA A LEITURA DELE


IMPORTE A CLASSE PESSOA E PASSE OS DADOS DO F5_POO/JSON PARA ESSA CLASSE


COMO ADIAR A EXECUÇÃO DE ALGO NO ARQUIVO PYTHON?


QUAL É NOME DO MODULO QUANDO EXECUTAMOS DIRETAMENTE?


COMO DESCOBRIR O NOME DO MODULO?


ESCREVA UMA CLASSE QUE SÓ EXECUTE O METODO DENTRO DELA SE O MODULO FOR ELE MESMO


PARA FAZER UM METODO DE CLASSE O QUE É NECESSARIO?


CONSTRUA UMA CLASSE PESSOA COM ATRIBUTO E METODO DE CLASSE:


O QUE É O DECORATOR @STATICMETHOD?


O QUE É O METHOD?
