1: O QUE SIGNIFICA O M  NO PYTHON3 -M VENV VENV?


2: COMO ECONTRAR A VERSAO DO PYTHON? 


3: COMO FAZER O UPGRADE DO PYTHON?


4: COMO EXECUTAR UM PROGRAMA PYTHON?


5: COMO LISTAR TODAS AS VERSOES DO PYENV?


6: COMO MOSTRAR QUAIS PYTHONS ESTAO INSTALADOS?


7: COMO DEFINIR O PYTHON PADRAO ATRAVES DO PYENV?


8: COMO FAZER UM TEXTO SER INTERPRETADO PELO PYTHON?


9: O DOCSTRING É UM COMENTARIO NO PYTHON?


10: COMO FUNCIONA O COMENTARIO NO INTERPRETADOR PYTHON?


-------------------------------------------------------------
SESSION 5
11111111111111

11: QUAL É UMA DAS PRIMEIRAS COISAS QUE É EXECUTADO QUANDO VOCE CHAMA A CLASSE?


12: COMO É CHAMADO A FUNÇÃO QUANDO ESTÁ DENTRO DA CLASSE?


13: QUAL É O PRIMEIRO PARAMETRO QUE PASSAMOS NO __INIT__?


14: COMO CRIAMOS UMA CLASSE PESSOA COM PARAMETROS DE NOME E SOBRENOME?


15: COMO COLOCAR COMPORTAMENTOS EM UMA CLASSE?


16: O METODO INIT RETORNA O QUE?


17: ESCREVA UMA CLASSE COM HARD CODED


18: O QUE É HARD CODED?


19: O QUE TODO METODO RECEBE COMO PRIMEIRO PARAMENTRO PARA REFERENCIAR A INSTANCIA NO PYTHON?


20: ESCREVA UMA CLASSE CARRO COM COMPORTAMENTO DE ACELERAR


21: O NOME SELF É UMA CONVENÇÃO?

11111111111111
---------------------------------------------------------------------------------------
22222222222222

22: UMA CLASSE PODE GERAR QUANTAS INSTANCIAS?


23: NA CLASSE O QUE É O SELF?


24: QUAL METODO É EXECUTADO QUANDO INSTANCIA A CLASSE?


25: DEFINA UMA VARIAVEL PARA SER EXECUTADA QUANDO INSTANCIAR A CLASSE SEM CHAMAR ESSA VARIAVEL


26: COMO É CHAMADO O ESCOPO DAS CLASSES E METODOS?


27: COMO DEFINIR ATRIBUTO DE CLASSE E ATRIBUTO DE INSTANCIA E COMO RETORNAR UM METODO DA CLASSE EM OUTRO METODO?


22222222222222
-------------------------------------------------------------------------------------------------------------------
33333333333333
ESCREVA UM CLASSE CAMERA PARA MANTER O ESTADOS (FILMAR, FOTOGRAFAR, PARA_DE_FILMAR) DENTRO DELA. REQUISITO DE QUANDO ESTIVER FILMANDO NÃO PODE FOTOGRAFAR


QUAIS AS DUAS MANEIRAS DE ACESSAR UM ATRIBUTO DE CLASSE?


ESCREVA UMA CLASSE COM ATRIBUTO DE ESCOPO DE CLASSE


33333333333333
---------------------------------------------------------------------------------------------
44444444444444

O QUE É O __DICT__?


COMO DELETAR UM DADO ATRIBUTO DE UMA CLASSE?


ONDE OS ATRIBUTOS DA CLASSE SÃO SALVOS?


QUAL A FUNÇÃO A QUE CONSEGUIMOS VER O __DICT__?


O __DICT__ É EDITAVEL? CONSTRUA UMA CLASSE!


CRIE UM DICIONARIO DE DADOS E DESEMPACOTE EM UMA CLASSE


PARA QUE SERVE O **KWARGS DO PYTHON?


CONSTRUA UMA CLASSE COM PROPRIEDADES E DEPOIS TENHA UM DICIONARIO DE DADOS E DESEMPACOTE ELES

44444444444444
---------------------------------------------
55555555555555
QUAL CONVENÇÃO DE NOME É UTILIZADA PARA CLASSE NO PYTHON?


QUAL CONVENÇÃO DE NOME É UTILIZADA PARA NOMES NO PYTHON?

 
CRIE UMA CLASSE PESSOA COM PROPRIEDADES DE NOME E SOBRENOME E SALVE OS DADOS DA CLASSE EM JSON


IMPORTE O MODULO CRIADO NO PYTHON PARA TER O CAMINHO DO ARQUIVO E FAÇA A LEITURA DELE


IMPORTE A CLASSE PESSOA E PASSE OS DADOS DO F5_POO/JSON PARA ESSA CLASSE


COMO ADIAR A EXECUÇÃO DE ALGO NO ARQUIVO PYTHON?


QUAL É NOME DO MODULO QUANDO EXECUTAMOS DIRETAMENTE?


COMO DESCOBRIR O NOME DO MODULO?


ESCREVA UMA CLASSE QUE SÓ EXECUTE O METODO DENTRO DELA SE O MODULO FOR ELE MESMO


PARA FAZER UM METODO DE CLASSE O QUE É NECESSARIO?


CONSTRUA UMA CLASSE PESSOA COM ATRIBUTO E METODO DE CLASSE:


O QUE É O DECORATOR @STATICMETHOD?


O QUE É O METHOD?


CONSTRUA UMA CLASSE COM STATICMETHOD E UTILIZE O ARGS E KWARGS NESSE METODO

55555555555555
-------------------------------------------------------------------------------------------------------------------------
66666666666666

O QUE O INIT FAZ E ELE É UMA METODO DE QUE?


O QUE É PROPERTY NO PYTHON?


QUAIS AS PRINCIPAIS SITUAÇÕES QUE É UTILIZADA O PROPERTY?


O QUE É CODIGO CLIENTE?


ESCREVA UM UM METODO DENTRO DE UMA CLASSE QUE SE COMPORTE COMO UMA PROPRIEDADE


QUAL A FUNÇÃO GERAL DE UM MÉTODO?


PARA ESCREVER UM SETTER NO MODO PYTHONICO O QUE É NECESSARIO?

 
QUANDO TEMOS UM UNDERLINE NA PROPRIEDADE OU NO QUE SIGNIFICA?


ESCREVA UMA CLASSE COM GETTER AND SETTER ONDE A PROPRIEDADE SÓ POSSA SER MUDADA PELO SETTER, NÃO PELO INIT

66666666666666
-------------------------------------------------------------------------------------------------------------------------
77777777777777

NO PYTHON EU TENHO MODIFICADORES DE ACESSO?


COMO É REPRESENTADO O MODIFICADOR DE ACESSO PUBLIC NO PYTHON?


COMO É REPRESENTADO O MODIFICADOR DE ACESSO PROTECTED NO PYTHON?


COMO É REPRESENTADO O MODIFICADOR DE ACESSO PRIVATE NO PYTHON?


O QUE É NAME MANGLING?


O QUE É ASSOCIAÇÃO EM OBJETOS PYTHON?


ESCREVA UMA CLASSE COM ASSOCIAÇÃO DE CLASSE ENTRE ESCRITOR E FERRAMENTA_DE_ESCREVER, GUARDE A ASSOCIAÇÃO DA FERRAMENTA_DE_ESCREVER NA PROPRIEDADE FERRAMENTA DA CLASSE ESCRITOR

77777777777777